id: IB141F4E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:31:51+00:00'
last_modified: '2022-06-16T05:34:33.146340+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8050
  title: ཕར་ཕྱིན་སྐབས་བརྒྱད་ཀྱི་དྲི་བ་དྲིས་ལན་ཐོས་བསམ་བློ་ཡི་རོལ་རྩེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DCB2:
      image_group_id: I1KG10324
      title: ''
      total_pages: 974
      order: 1
      base_file: DCB2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
